# Generated by Django 3.2 on 2023-05-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0002_alter_car_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='miles',
            new_name='kilometers',
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_consumption',
            field=models.FloatField(verbose_name='Fuel Consumption (L/100km)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(verbose_name='Price (AUD)'),
        ),
    ]
