# Generated by Django 3.2 on 2023-05-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0005_alter_car_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='color',
            new_name='colour',
        ),
    ]
