# Generated by Django 3.2 on 2023-05-24 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0006_rename_color_car_colour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts_app', '0002_rename_create_date_contact_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='car_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars_app.car'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
